services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: enrollment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - suthub

  enrollment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enrollment-api
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    depends_on:
      - rabbitmq
    networks:
      - suthub
    volumes:
      - ./:/app

  processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: processor
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: python processor/worker.py
    depends_on:
      - rabbitmq
      - enrollment-api
    networks:
      - suthub
    volumes:
      - ./:/app


networks:
  suthub:
    external: true
